name: Patch Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
           echo "PATCHVBMETAFLAG=true" >> $GITHUB_ENV
           sudo apt-get update && sudo apt-get install -y tree p7zip-full aria2
     

    - name: download boot
      uses: dawidd6/action-download-artifact@master
      with:
        repo: liaoke01/BootIMGExtractAction
        workflow_conclusion: success
        workflow: BootIMGExtractAction.yml
        name: boot.img
        path: .

    - name: Download magiskboot
      run: |
        wget https://github.com/xiaoxindada/magiskboot_ndk_on_linux/releases/latest/download/magiskboot.7z
        7z x magiskboot.7z
        mv out/x86_64/magiskboot .
        chmod 777 magiskboot
        ./magiskboot unpack boot.img
        tree
        rm kernel
        
    - name: unzip
      run: |
        aria2 https://github.com/liaoke01/image-boot.img/blob/main/1.zip
        7z x 1.zip "Image"
        mv Image kernel
        

    - name: build boot.img
      run: |
           tree
           ./magiskboot repack boot.img
           tree
           find . -maxdepth 1 ! -name 'magiskboot' ! -name 'new-boot.img' -exec rm -rf {} \;
           tree

    - name: Get latest tag from bmax121/kernelpatch
      id: latest_tag_kernelpatch
      run: |
        # 使用GitHub API获取bmax121/kernelpatch的最新tag
        latest_tag_response=$(curl -s https://api.github.com/repos/bmax121/kernelpatch/tags)
        # 解析JSON响应以获取最新tag
        latest_tag=$(echo "$latest_tag_response" | grep -o '"name":.*' | head -n 1 | cut -d '"' -f 4)
        echo "Latest tag is: $latest_tag"
        # 设置输出变量
        echo "::set-output name=tag::$latest_tag"

    - name: Set download URLs with latest tag from bmax121/kernelpatch
      run: |
        # 更新kptools-linux的下载链接
        echo "KP_TOOLS_URL=https://github.com/bmax121/KernelPatch/releases/download/${{ steps.latest_tag_kernelpatch.outputs.tag }}/kptools-linux" >>$GITHUB_ENV
        # 更新kpimg-android的下载链接
        echo "KP_IMG_URL=https://github.com/bmax121/KernelPatch/releases/download/${{ steps.latest_tag_kernelpatch.outputs.tag }}/kpimg-android" >>$GITHUB_ENV
    
    - name: Download files
      run: |
        aria2c -o kpimg-android $KP_IMG_URL
        aria2c -o kptools-linux $KP_TOOLS_URL
        mv kptools-linux kptools
        mv kpimg-android kpimg
        chmod 777 kptools
        mv new-boot.img boot.img
        ./magiskboot unpack boot.img
        mv kernel kernel-b
        ./kptools -p --image kernel-b --skey "lk88888888" --kpimg kpimg --out kernel
        ./magiskboot repack boot.img
        tree

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: new-boot.img
        path: new-boot.img
