name: Patch Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
           echo "PATCHVBMETAFLAG=true" >> $GITHUB_ENV
           sudo apt-get update && sudo apt-get install -y tree p7zip
     

    - name: download boot
      uses: dawidd6/action-download-artifact@master
      with:
        repo: liaoke01/BootIMGExtractAction
        workflow_conclusion: success
        workflow: BootIMGExtractAction.yml
        name: boot.img
        path: .

    - name: Download magiskboot
      run: |
        wget https://github.com/xiaoxindada/magiskboot_ndk_on_linux/releases/latest/download/magiskboot.7z
        7z x magiskboot.7z
        mv out/x86_64/magiskboot .
        chmod 777 magiskboot
        
    - name: download boot
      uses: dawidd6/action-download-artifact@master
      with:
        repo: liaoke01/BootIMGExtractAction
        workflow_conclusion: success
        workflow: BootIMGExtractAction.yml
        name: boot.img
        path: .


    - name: build boot.img
      run: |
           ./magiskboot unpack boot.img
           tree
           rm kernel
           wget https://120-232-77-35.pd1.123pan.cn:30443/download-cdn.123pan.cn/123-924/11f9fb4d/1812077907-0/11f9fb4d53557c3e59a121f75e23c39c/c-m39?v=5&t=1718520444&s=1718520444875b6b779e7d75c9d927880ee85bc432&r=RZBX90&bzc=1&bzs=1812077907&filename=kernel&x-mf-biz-cid=fa794184-356d-4319-9a62-9a7be14611fd-584000&auto_redirect=0&ndcp=1&cache_type=1&xmfcid=25f56773-7806-4f31-bb20-91630252a494-1-50111d3b1
           tree
           ./magiskboot repack
           tree


  
   
